
#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int spin = 10;
	int mode = 1;

	while(true)

	{

		if(mode ==1)

		{

				motor[Left] = spin;

				motor[Right] = spin + 20;

				wait1Msec(500);
				resetMotorEncoder(Left);

				spin = spin + 2;

				if(SensorValue(button) == 1)
				{
					mode = 2;
				}
		}
					if(mode==2)
					{
						motor[Right] =-100; motor[Left]= -100;
						wait1Msec(500);
						motor[Right]=0; motor[Left] = -100;
						wait1Msec(500);
							while(SensorValue(button)==0)
						{
							motor[Right]=60; motor[Left] =100;
							wait1Msec(100);
						}


						if(getMotorEncoder(Left)> 3000)
						{
							motor[Right]=-100; motor[Left]=-100;
							wait1Msec(500);
							motor[Right]=100; motor[Left]=0;
							wait1Msec(1000);
							mode=3;
							resetMotorEncoder(Left);
						}
					}
						if(mode==3)
						{
							motor[Right]=100; motor[Left]=100;
								if(getMotorEncoder(Left)>5000)
								{
									mode=1;
									spin=10;
								}
									if(SensorValue(button)==1)
									{
										mode=2;
										resetMotorEncoder(Left);
									}
						}




}
































}
