#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, encoder)
 #pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, encoder)
 //*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int mode=1;

		while(true)
		{
			if(mode== 1)
			{
				motor[Left]=100;
				motor[Right]=100;
					if(getMotorEncoder(Left) >1000)
					{
						mode=2;
						resetMotorEncoder(Left);
					}
			}
					if(mode==2)
					{
						motor[Left]=-100;
						motor[Right]=-100;
							if(getMotorEncoder(Left) >1000)
							{
								mode= 1;
								resetMotorEncoder(Left);
							}
					}
		}


}
