
#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[Right] =100; motor[Left] =100;
		wait1Msec(100);

		if(SensorValue(button)==1)
		{
			motor[Right] =-100; motor[Left]= -100;
			wait1Msec(250);
			motor[Right]=0; motor[Left] = -100;
			wait1Msec(500);
		 		while(SensorValue(button)==0)
  			{
					motor[Right]=60; motor[Left] =100;
  				wait1Msec(100);
				}
		}

	}
}
